### ISSUE TITLE
Not getting the response from all tasks?

### ISSUE THREAD

**Issue by sayanb** [asyncphp/doorman#27]
`
	<?php

	use AsyncPHP\Doorman\Manager\ProcessManager;
	use AsyncPHP\Doorman\Task\ProcessCallbackTask;
	use AsyncPHP\Remit\Client\ZeroMqClient;
	use AsyncPHP\Remit\Server\ZeroMqServer;
	use AsyncPHP\Remit\Location\InMemoryLocation;

	class Localtest extends CI_Controller {

		public function index() {
			try {
				$numTasks = 10;
				$manager = new ProcessManager();
				echo("\ncreated manager");
				$server = new ZeroMqServer(
				   	new InMemoryLocation("127.0.0.1", 5555)
				);
				echo("\ncreated server");
				$server->addListener("message-from-child-process", function ($message) {
					echo("\nmessage from child process: {$message}");
				});
				echo("\nadded listener");

				for ($i = 0; $i < $numTasks; $i++) { 
					if ($task = $this->getNextTask()) {
			      		$manager->addTask($task);
			      		echo("\nadded task");
			   		}
				}

				while ($manager->tick()) {
					echo("\nlistening");
					$server->tick();
		    		        usleep(250);
				}
			} catch (Error $e) {
				echo($e->getMessage());
			} catch (Exception $e) {
				echo($e->getMessage());
			}
		}

		private function getNextTask() {
			try {
				$task = new ProcessCallbackTask(function () {
					echo("\nin child");
				    $client = new ZeroMqClient(
					new InMemoryLocation("127.0.0.1", 5555)
				    );

				    $data = "hello man";
				    $client->emit(
					"message-from-child-process", [$data]
				    );
				});
				return $task;
			} catch (Error $e) {
				echo($e->getMessage());
			} catch (Exception $e) {
				echo($e->getMessage());
			}
		}
	}
`

Expected output: Seeing the data (the string "hello man") 10 times, for 10 tasks. 

Actual output:

created manager
created server
added listener
added task
added task
added task
added task
added task
added task
added task
added task
added task
added task
listening
listening
**message from child process: hello man**

So I see the output just once, instead of 10 times. Could you please help me understand what's going wrong?

**Comment by assertchris** [comment]
Hmmm. At first glance, I can't think what the problem could be. Would it be possible to push the project to git so I can clone and run the app to debug?

**Comment by sayanb** [comment]
Hi @assertchris , sure. Here it is: https://github.com/sayanb/doorman-test

To execute, just need to run

php index.php 

from the CLI. You'll just need to install Doorman and Remit.

**Comment by assertchris** [comment]
Sorry for the delay. From what I can tell, it looks like the PID being returned and stored in the launching of each `ProcessCallbackTask` is different from the list of returned processes when queried. Every check to see if the spawned process is still running returns `false`, and the `processing` and `waiting` lists are empty. `$manager->tick()` returns false, and `$server->tick()` never happens. I don't see any messages from the child processes...

Since you're seeing at least 1 message, I'm going to assume your PID values are more accurate on your system than they are on mine. Perhaps the tasks aren't staying open long enough to send their messages and for `$manager->tick()` to return `true` so that `$server->tick()` picks up the messages.

Try adding a really long sleep to the child process tasks, so that they stay open through multiple `$manager->tick()`'s...

**Comment by assertchris** [comment]
As a side-note: I really don't like how this process management works anymore. Would it be possible for you to use something like https://github.com/amphp/parallel-functions in your codebase, instead? There are functions to make the "manager" behave in a synchronous environment, but for all the tasks to be executed in parallel processes...

**Comment by sayanb** [comment]
Thanks @assertchris , I may give https://github.com/amphp/parallel-functions a try!

**Comment by sayanb** [comment]
@assertchris  https://github.com/amphp/parallel-functions is working much better for me!

**Comment by assertchris** [comment]
Great news! I've put some suggestions here, for the next person to try. Gonna close, in the meantime.
